vich_uploader:
    db_driver: orm

    mappings:
      questions_image:
        uri_prefix: /images/questions
        upload_destination: '%kernel.project_dir%/public/images/questions'
        namer: Vich\UploaderBundle\Naming\UniqidNamer

      activity_image:
        uri_prefix: /images/activity
        upload_destination: '%kernel.project_dir%/public/images/activity'
        namer: Vich\UploaderBundle\Naming\UniqidNamer

      import_csv:
        uri_prefix: '/csv'
        upload_destination: '%kernel.project_dir%/public/csv'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
